services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=streaming_play_db'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=sebastian'
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
